name: Update Language Metrics
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  analyze-languages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install Linguist
      run: gem install github-linguist
      
    - name: Analyze Repository Languages
      id: linguist
      run: |
        echo "LANGUAGES=$(github-linguist --json)" >> $GITHUB_OUTPUT
        
    - name: Update README
      uses: juliangruber/readme-badge-action@v1
      with:
        badge: "languages-${{ steps.linguist.outputs.LANGUAGES }}"
